const AEL = require ("./AE_libray");
const { toChecksumAddress } = require('ethereum-checksum-address')
const AEUW = require ("./AE_wallet_user");
const AEEW = require ("./AE_wallet_entity");

async function main() {

    console.log ("INIT TESTING");

    console.log ("1st test: create HDWallets");
    let newUserEpicWallet = new AEUW.AE_userWallet();
    newUserEpicWallet.setMnemonic("used rebel ahead harvest journey steak hub core opera wrong rate loan");
    newUserEpicWallet.setIdentityDerivation("m/1037171/131071/0407/10011001/94367/3651441");
    newUserEpicWallet.addBPlusDerivation("AcmeAcademy","6385471");

    let newEntityEpicWallet = new AEEW.AE_entityWallet();    
    newEntityEpicWallet.setMnemonic("manage wage hill kitten joke buyer topic focus observe valid december oyster");
    newEntityEpicWallet.setIdentityDerivation("m/1037171/131071/0407/10011001/96278543/2564789");
    newEntityEpicWallet.addCPlusDerivation("User","241573");

  
    
    var  credentialText = ' {' +
        '"@context": [' +
        '  "https://www.w3.org/2018/credentials/v1",' +
        '  "https://www.w3.org/2018/credentials/examples/v1"' +
        '],' +
        'id": "http://example.edu/credentials/58473",' +
        '"type": ["VerifiableCredential", "AlumniCredential"],' +
        '"issuer": "$ISSUER",' +
        '"issuanceDate": "2010-01-01T00:00:00Z",' +
        '"credentialSubject": {' +
        '  "id": "$SUBJECT",' +
        '  "alumniOf": {' +
        '    "id": "$SCHOOL",' +
        '    "name": [{' +
        '      "value": "AcmeAcademy",' +
        '      "lang": "en"' +
        '    }]' +
        '  }' +
        '} ' +   
      '}';
    
    // Replace in the credential the ISSUER with Issuer's ExtendedPublicKey
    credentialText = credentialText.replace("$ISSUER",newEntityEpicWallet.credencialIssuance_extPublicKey);


    // Replace in the credential the SCHOOL with the School's ExtentendedPublicKey
    // in this case Issuer = School but Issuer's ExtendedPublicKey is the credencialIssuance
    // and the school is the base, this is atipical     
    credentialText = credentialText.replace("$SCHOOL",newEntityEpicWallet.identity_ExtPublicKey);
   
    // The credential is issued to a subject, we must use the subject DID or ExtendedPublicKey in the subject
    // To get the ExtendedPublicKey the subject should create a three level derivation: he chooses the first to levels and the entity tells the user the
    // third level, this can change to more levels for security against pre-image attacks
    // Also for identification issues each sigle credential should have a different ID
    newUserEpicWallet.setCredentialDerivation("AcmeAcademy","4b860b60-dd5a-4c3c-ab59-f02252b42772","1251679543");
    subjectPublicKey = newUserEpicWallet.getCredentialExtendedPublicKey("AcmeAcademy","4b860b60-dd5a-4c3c-ab59-f02252b42772","1251679543");


    // Also the credential is issued to a subject, the standard is the "m/1" derivation from the subject identity used for the realtionship with the school
    // in this case it would be 241573/1 (as opposed to 241573/0 used for the login)
    AcmeAcademy = newUserEpicWallet.getBPlusDerivation("AcmeAcademy");
    user_acme_relationship_wallet = AEL.getHDWalletDerivation(newUserEpicWallet.identity_HDWallet , "m/" + AcmeAcademy.B_derivation);

    // I tell AcmeAcademy my user_acme_relationship_public_key, that is equivalent to my DID only for AcmeAcademy
    user_acme_relationship_public_key = AEL.getPublicExtendedKey(user_acme_relationship_wallet);

    // Then AcmeAcademy can calculate my ExtendedPublicKey for VC issuance, that would be derivation "m/1"
    // But that will not be the wallet where the user will receive the VC, we need an extra derivation: 
    // At least 2 user generated derivations (D) and one entity generated derivation (E)
    // /2128469835/1325276260 are generated by the user, /1251679543 is generated by AcmeAcademy
    // so the final DID for the VC for the user will be /1/810906238/253622342/1251679543 in addition to his AcmeAcademy already generated Wallet
    user_acme_VC_wallet = AEL.createRO_HDWalletFromPublicExtendedKey(user_acme_relationship_public_key);
    user_acme_VC_wallet = AEL.getHDWalletDerivation(user_acme_VC_wallet, "m/1/810906238/253622342/1251679543");
    subjectPublicKey = AEL.getPublicExtendedKey(user_acme_VC_wallet);
    credentialText = credentialText.replace("$SUBJECT",subjectPublicKey);

    // AcmeAcademy will also sign the VC, it will use "/1" derivation of his identity to such purposes, this derivation will be independent of the user so it is easy to validate
    acme_vc_signer_eWallet = 
    AEL.getEthereumWalletFromPrivateKey(
        AEL.getPrivateKeyFromExtended(
            AEL.getPrivateExtendedKey(newEntityEpicWallet.credencialIssuance_HDWallet)
            )
        );

    let acme_user_VC_signature = await AEL.signMessage(acme_vc_signer_eWallet, credentialText);   

    // and the user (or anyone) can verify the signature
    // we do teh calculation from the getPublicExtendedKey(base_HDWallet) that will be the registered publicKey in the SmartContract
    AEL.verifyMessageByPublicExtendedKey(credentialText,acme_user_VC_signature, 
        AEL.getPublicExtendedKey(
            AEL.getHDWalletDerivation(
                AEL.createRO_HDWalletFromPublicExtendedKey(
                    AEL.getPublicExtendedKey(
                        newEntityEpicWallet.base_HDWallet
                    )
                ),
                "m/1"
            )
        )
    );

    console.log(credentialText);


}

main ();
